In [2]:
import pandas as pd
import numpy as np


In [3]:
# Read the dataset
df1 = pd.read_csv("G-prediction.csv")
df1

height  weight beard hair_length  shoe_size scarf eye_color  gender
0       71     176   yes       short         44    no     black    male
1       68     165    no        bald         41    no     black    male
2       62     132    no      medium         37   yes      blue  female
3       65     138    no        long         38    no      gray  female
4       70     197   yes      medium         43    no      gray    male
..     ...     ...   ...         ...        ...   ...       ...     ...
75      65      99    no       short         39   yes     green  female
76      61      98    no       short         37    no     brown  female
77      67     119   yes       short         40    no     black    male
78      70     190   yes      medium         43    no      gray    male
79      62     142   yes        long         37    no      blue  female

[80 rows x 8 columns]

In [24]:
# Import LabelEncoder
from sklearn import preprocessing

# Creating labelEncoder
le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
df1['beard']=le.fit_transform(df1['beard'])
df1['hair_length']=le.fit_transform(df1['hair_length'])
df1['scarf']=le.fit_transform(df1['scarf'])
df1['eye_color']=le.fit_transform(df1['eye_color'])
df1['gender']=le.fit_transform(df1['gender'])
df1

height  weight  beard  hair_length  shoe_size  scarf  eye_color  gender
0       71     176      1            3         44      0          0       1
1       68     165      0            0         41      0          0       1
2       62     132      0            2         37      1          1       0
3       65     138      0            1         38      0          3       0
4       70     197      1            2         43      0          3       1
..     ...     ...    ...          ...        ...    ...        ...     ...
75      65      99      0            3         39      1          4       0
76      61      98      0            3         37      0          2       0
77      67     119      1            3         40      0          0       1
78      70     190      1            2         43      0          3       1
79      62     142      1            1         37      0          1       0

[80 rows x 8 columns]

In [25]:
x = df1[['height','weight','beard','hair_length','shoe_size','scarf','eye_color']]
y = df1['gender']

#Spliting Data for traning(67%) and testing(33%)
from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.33,random_state=42)

#Spliting Data for traning(80%) and testing(20%)
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.20,random_state=42)

In [26]:
# Import MLPClassifer 
from sklearn.neural_network import MLPClassifier

# Create model object
clf = MLPClassifier(hidden_layer_sizes=(6,5),
                    random_state=5,
                    verbose=True,
                    learning_rate_init=0.01)

# Fit data onto the model
clf.fit(X_train,y_train)

Iteration 1, loss = 5.64997221
Iteration 2, loss = 3.45929966
Iteration 3, loss = 1.57176097
Iteration 4, loss = 0.77516152
Iteration 5, loss = 0.82527551
Iteration 6, loss = 0.82397467
Iteration 7, loss = 0.81227197
Iteration 8, loss = 0.80446194
Iteration 9, loss = 0.80574566
Iteration 10, loss = 0.79584830
Iteration 11, loss = 0.77731126
Iteration 12, loss = 0.75324756
Iteration 13, loss = 0.72668889
Iteration 14, loss = 0.70042260
Iteration 15, loss = 0.67681184
Iteration 16, loss = 0.65759566
Iteration 17, loss = 0.64384214
Iteration 18, loss = 0.63586852
Iteration 19, loss = 0.63324351
Iteration 20, loss = 0.63492310
Iteration 21, loss = 0.63946666
Iteration 22, loss = 0.64529339
Iteration 23, loss = 0.65093687
Iteration 24, loss = 0.65524239
Iteration 25, loss = 0.65747879
Iteration 26, loss = 0.65736253
Iteration 27, loss = 0.65501850
Iteration 28, loss = 0.65084973
Iteration 29, loss = 0.64549801
Iteration 30, loss = 0.63965085
Training loss did not improve more than tol=0.000

MLPClassifier(hidden_layer_sizes=(6, 5), learning_rate_init=0.01,
              random_state=5, verbose=True)

In [27]:
# Make prediction on test dataset
ypred=clf.predict(X_test)

# Import accuracy score 
from sklearn.metrics import accuracy_score

# Calcuate accuracy
accuracy_score(y_test,ypred)

0.5625

In [28]:
from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(y_test,ypred))

print(classification_report(y_test,ypred))


[[0 7]
 [0 9]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         7
           1       0.56      1.00      0.72         9

    accuracy                           0.56        16
   macro avg       0.28      0.50      0.36        16
weighted avg       0.32      0.56      0.40        16



C:\Users\4a\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\4a\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\4a\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [29]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
rf_clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
rf_clf.fit(X_train,y_train)

random_y_pred=rf_clf.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(y_test,random_y_pred))

print(classification_report(y_test,random_y_pred))

[[7 0]
 [0 9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         9

    accuracy                           1.00        16
   macro avg       1.00      1.00      1.00        16
weighted avg       1.00      1.00      1.00        16



In [30]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
svm_clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
svm_clf.fit(X_train, y_train)

#Predict the response for test dataset
svm_pred = svm_clf.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(y_test,svm_pred))

print(classification_report(y_test,svm_pred))

[[7 0]
 [0 9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         9

    accuracy                           1.00        16
   macro avg       1.00      1.00      1.00        16
weighted avg       1.00      1.00      1.00        16



In [31]:
df2=df1.drop('weight', axis = 1, inplace = True)
df2=df1.drop('beard', axis = 1, inplace = True)
print(df1)

    height  hair_length  shoe_size  scarf  eye_color  gender
0       71            3         44      0          0       1
1       68            0         41      0          0       1
2       62            2         37      1          1       0
3       65            1         38      0          3       0
4       70            2         43      0          3       1
..     ...          ...        ...    ...        ...     ...
75      65            3         39      1          4       0
76      61            3         37      0          2       0
77      67            3         40      0          0       1
78      70            2         43      0          3       1
79      62            1         37      0          1       0

[80 rows x 6 columns]


In [32]:
x = df1[['height','hair_length','shoe_size','scarf','eye_color']]
y = df1['gender']

from sklearn.model_selection import train_test_split
#Spliting Data for traning(80%) and testing(20%)
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.20,random_state=42)

In [33]:
# Import MLPClassifer 
from sklearn.neural_network import MLPClassifier

# Create model object
clf = MLPClassifier(hidden_layer_sizes=(6,5),
                    random_state=5,
                    verbose=True,
                    learning_rate_init=0.01)

# Fit data onto the model
clf.fit(X_train,y_train)

# Make prediction on test dataset
ypred=clf.predict(X_test)

# Import accuracy score 
from sklearn.metrics import accuracy_score

# Calcuate accuracy
accuracy_score(y_test,ypred)

from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(y_test,ypred))

print(classification_report(y_test,ypred))

Iteration 1, loss = 2.14059145
Iteration 2, loss = 1.76845084
Iteration 3, loss = 1.43778079
Iteration 4, loss = 1.15822924
Iteration 5, loss = 0.94517806
Iteration 6, loss = 0.80696025
Iteration 7, loss = 0.73588020
Iteration 8, loss = 0.68889796
Iteration 9, loss = 0.68105369
Iteration 10, loss = 0.68111180
Iteration 11, loss = 0.68117090
Iteration 12, loss = 0.68122931
Iteration 13, loss = 0.68128582
Iteration 14, loss = 0.68133962
Iteration 15, loss = 0.68139013
Iteration 16, loss = 0.68143697
Iteration 17, loss = 0.68147994
Iteration 18, loss = 0.68151890
Iteration 19, loss = 0.68155384
Iteration 20, loss = 0.68158479
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
[[0 7]
 [0 9]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         7
           1       0.56      1.00      0.72         9

    accuracy                           0.56        16
   macro avg       0.28      0.50      0.36   

C:\Users\4a\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\4a\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\4a\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [34]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
rf_clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
rf_clf.fit(X_train,y_train)

random_y_pred=rf_clf.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(y_test,random_y_pred))

print(classification_report(y_test,random_y_pred))

[[6 1]
 [0 9]]
              precision    recall  f1-score   support

           0       1.00      0.86      0.92         7
           1       0.90      1.00      0.95         9

    accuracy                           0.94        16
   macro avg       0.95      0.93      0.94        16
weighted avg       0.94      0.94      0.94        16



In [35]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
svm_clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
svm_clf.fit(X_train, y_train)

#Predict the response for test dataset
svm_pred = svm_clf.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(y_test,svm_pred))

print(classification_report(y_test,svm_pred))

[[6 1]
 [0 9]]
              precision    recall  f1-score   support

           0       1.00      0.86      0.92         7
           1       0.90      1.00      0.95         9

    accuracy                           0.94        16
   macro avg       0.95      0.93      0.94        16
weighted avg       0.94      0.94      0.94        16



In [4]:
#Againg Read the dataset with complete rows and columns
# Read the dataset
df3 = pd.read_csv("G-prediction.csv")
# df3

# Import LabelEncoder
from sklearn import preprocessing

# Creating labelEncoder
le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
df3['beard']=le.fit_transform(df3['beard'])
df3['hair_length']=le.fit_transform(df3['hair_length'])
df3['scarf']=le.fit_transform(df3['scarf'])
df3['eye_color']=le.fit_transform(df3['eye_color'])
df3['gender']=le.fit_transform(df3['gender'])
df3

x = df3[['height','weight','beard','hair_length','shoe_size','scarf','eye_color']]
y = df3['gender']

#Spliting Data for traning(67%) and testing(33%)
from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.33,random_state=42)

#Spliting Data for traning(80%) and testing(20%)
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.20,random_state=42)



df3

height  weight  beard  hair_length  shoe_size  scarf  eye_color  gender
0       71     176      1            3         44      0          0       1
1       68     165      0            0         41      0          0       1
2       62     132      0            2         37      1          1       0
3       65     138      0            1         38      0          3       0
4       70     197      1            2         43      0          3       1
..     ...     ...    ...          ...        ...    ...        ...     ...
75      65      99      0            3         39      1          4       0
76      61      98      0            3         37      0          2       0
77      67     119      1            3         40      0          0       1
78      70     190      1            2         43      0          3       1
79      62     142      1            1         37      0          1       0

[80 rows x 8 columns]

In [40]:

#With MonteCarlo cross validation

from sklearn.model_selection import ShuffleSplit,cross_val_score
from sklearn.tree import DecisionTreeClassifier

dt=DecisionTreeClassifier()
shuffle_split=ShuffleSplit(test_size=0.3,train_size=0.5,n_splits=10)

scores=cross_val_score(dt,x,y,scoring="f1",cv=shuffle_split)

print("cross Validation scores:n {}".format(scores))
print("Average Cross Validation score :{}".format(scores.mean()))



cross Validation scores:n [0.96551724 0.83333333 0.96774194 0.9        0.96774194 0.90909091
 0.96774194 0.96296296 1.         1.        ]
Average Cross Validation score :0.9474130253218128


In [41]:
#With P-Out cross validation
from sklearn.model_selection import LeavePOut,cross_val_score
from sklearn.tree import DecisionTreeClassifier

#  Ignore the unnecessary warnings
import warnings
warnings.filterwarnings('ignore')

lpo=LeavePOut(p=2)
lpo.get_n_splits(x)
tree=DecisionTreeClassifier(max_depth=5)
score=cross_val_score(tree,x,y,scoring="f1",cv=lpo)
print("Cross Validation Scores are {}".format(score))
print("Average Cross Validation score :{}".format(score.mean()))

Cross Validation Scores are [1.         1.         1.         ... 1.         0.66666667 0.66666667]
Average Cross Validation score :0.7761603375527427


In [42]:
#create dataframe
df_new_rows = pd.DataFrame(df3)
print('Original DataFrame\n------------------')
print(df_new_rows.head(15))

new_row = [{'height':67,'weight':126,'beard':1,'hair_length':3,'shoe_size':42,"scarf":0,'eye_color':1,'gender':1},#Hasnain Ali
           {'height':66,'weight':132,'beard':1,'hair_length':0,'shoe_size':42,"scarf":0,'eye_color':2,'gender':1},#Abdul_Baseer
           {'height':68,'weight':140,'beard':0,'hair_length':1,'shoe_size':40,"scarf":0,'eye_color':1,'gender':1},#Sudais
           {'height':65,'weight':200,'beard':0,'hair_length':3,'shoe_size':42,"scarf":0,'eye_color':1,'gender':1},#Huzaifa
           {'height':68,'weight':130,'beard':1,'hair_length':2,'shoe_size':40,"scarf":0,'eye_color':3,'gender':1}]#Azeem             
#append row to the dataframe
df_new_rows = df_new_rows.append(new_row, ignore_index=True)

print('\n\nNew row added to DataFrame\n--------------------------')
print(df_new_rows)

Original DataFrame
------------------
    height  weight  beard  hair_length  shoe_size  scarf  eye_color  gender
0       71     176      1            3         44      0          0       1
1       68     165      0            0         41      0          0       1
2       62     132      0            2         37      1          1       0
3       65     138      0            1         38      0          3       0
4       70     197      1            2         43      0          3       1
5       71     190      1            3         43      0          0       1
6       74     201      1            0         44      0          2       1
7       74     182      0            3         46      0          2       1
8       63     127      0            3         35      0          4       0
9       65     139      0            2         37      1          3       0
10      66     125      0            1         36      0          3       0
11      73     188      1            3         42 

[[5 2]
 [0 9]]
              precision    recall  f1-score   support

           0       1.00      0.71      0.83         7
           1       0.82      1.00      0.90         9

    accuracy                           0.88        16
   macro avg       0.91      0.86      0.87        16
weighted avg       0.90      0.88      0.87        16



In [43]:
a = df_new_rows[['height','weight','beard','hair_length','shoe_size','scarf','eye_color']]
b = df_new_rows['gender']

#Spliting Data for traning(67%) and testing(33%)
from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.33,random_state=42)

#Spliting Data for traning(80%) and testing(20%)
X_train, X_test, y_train, y_test = train_test_split(a,b,test_size=0.20,random_state=42)

In [44]:
#Fitting Naive Bayes classification to the Training set
from sklearn.naive_bayes import GaussianNB
nbclassifier = GaussianNB()
nbclassifier.fit(X_train,y_train)

#Predicting the test set result
Y_predicts= nbclassifier.predict(X_test)
Y_predicts

#Confusion Matrix diagonal values are Correct predidted values.
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,Y_predicts))

print(classification_report(y_test,Y_predicts))

[[ 6  1]
 [ 0 10]]
              precision    recall  f1-score   support

           0       1.00      0.86      0.92         7
           1       0.91      1.00      0.95        10

    accuracy                           0.94        17
   macro avg       0.95      0.93      0.94        17
weighted avg       0.95      0.94      0.94        17

